apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: activerecord-import
  description: "A library for bulk insertion of data into your database using ActiveRecord."
  annotations:
    github.com/project-slug: justworkshr/activerecord-import
    tags:
    - ruby
spec:
  lifecycle: production
  type: library
  owner: dev-ex
